<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ivaan" ignored="0" name="Listeners" tests="7" failures="1" timestamp="2019-09-05T07:24:35 CDT" time="2.789" errors="0">
  <testcase name="addInt" time="0.01" classname="org.spring.demo.test.TestEmployee"/>
  <testcase name="getEmployeeListTestNE" time="0.241" classname="org.spring.demo.test.TestEmployee"/>
  <testcase name="getEmployeeTest" time="0.007" classname="org.spring.demo.test.TestEmployee"/>
  <testcase name="getEmployeeTestNE" time="0.006" classname="org.spring.demo.test.TestEmployee"/>
  <testcase name="getEmployeeListTest" time="0.009" classname="org.spring.demo.test.TestEmployee"/>
  <testcase name="addInt" time="0.001" classname="org.spring.demo.test.TestEmployeeLisnr"/>
  <testcase name="addIntFail" time="0.001" classname="org.spring.demo.test.TestEmployeeLisnr">
    <failure type="java.lang.AssertionError" message="expected [5] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [4]
at org.spring.demo.test.TestEmployeeLisnr.addIntFail(TestEmployeeLisnr.java:39)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- addIntFail -->
</testsuite> <!-- Listeners -->
